### PR TITLE
Minor formating updates to README

### PR DESCRIPTION
**Pull request by Aloran6**
All original information are retained

### CODE REVIEW

**Comment by laggycomputer** [comment]
I think that the grammar on this is still a tidbit problematic.

**Comment by laggycomputer** [comment]
Does https://github.com/laggycomputer/suprkewl-bot/commit/7de0ef3da94c5ab14f546756937cb70e4e9bc202 address your updates?

**Comment by laggycomputer** [comment]
Does https://github.com/laggycomputer/suprkewl-bot/commit/ddd20af96539676ce3b223bb883cfd87420df9d3 address your updates?

**Comment by Aloran6** [comment]
More or less, is it possible to first merge my pull request and then merge
yours? This is for an assignment at school I would really appreciate it if
you would help me out. I just need a screenshot of the merge.

Thank you so much!

**Comment by laggycomputer** [comment]
Here you are! Good luck in school, this seems like a fun class if it covers open source projects.
image

**Pull request merged**
